apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: bochan
        - name: RABBITMQ_DEFAULT_PASS
          value: bochan
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
    - name: mqtt
      port: 1883
      targetPort: 1883
  selector:
    app: rabbitmq