apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: monitoring
data:
  telegraf.conf: |
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      omit_hostname = false

    [[outputs.influxdb_v2]]
      urls = ["http://1.247.226.190:8086"]
      token = "AAN7rGgxofhx_V97JL0OWKedoIm-lkD4LRofbStsm9WYtMy3BfrL336s0WAzb7gbVWnvHZ--V029WFRnq0UAHQ=="
      organization = "bochanspace"
      bucket = "client-resource"

    [[inputs.amqp_consumer]]
      brokers = ['amqp://bochan:bochan@1.247.226.190:5672/']
      exchange = "edge-resource-exchange"
      exchange_type = "direct"
      exchange_durability = "durable"
      queue = "Store_To_DB"
      queue_durability = "durable"
      binding_key = "info"
      data_format = "influx"
